blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/armanayvazyan/propsy/discussions
    about: Ask questions and discuss ideas with the community.
